apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wmzt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-wmzt@sha256:5b41b0d012735af4519f6a10d8400d96881cdfa67e1d8a772abfd53d24b132d4
        name: my-nodejs
        resources: {}
status: {}
